name: Frontend Continuous Integration

on:
  push:
    branches:
      -main
  pull_request:
    branches:
      - main
  workflow_dispatch:    

defaults:
  run:
    working-directory: starter

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json
      - name: Install dependencies
        run: npm ci
        working-directory: starter/frontend
      - name: Run linter
        run: npm run lint
        working-directory: starter/frontend


  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json
      - name: Install dependencies
        run: npm ci
        working-directory: starter/frontend
      - name: Run the tests
        run: CI=true npm test
        working-directory: starter/frontend

  Build:
    needs: [Lint, Test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json
      - name: Install dependencies
        run: npm ci
        working-directory: starter/frontend
      - name: Build docker image
        run: docker build --build-arg=REACT_APP_MOVIE_API_URL=http://localhost:5000 --tag=mp-frontend:latest .
      - name: Run container
        run: docker run --name mp-frontend -p 3000:3000 -d mp-frontend